SELECT TOP (1000) [timestamp]
      ,[Document Type]
      ,[Document No_]
      ,[Line No_]
      ,[Purchase Document No_]
      ,[Purchase Document Type]
      ,[Purchase Document Line No_]
      ,[Equipment Object]
       ,[Catalogue No_]
      ,[Equipment Configurator No_]
      ,[Responsibility Center]
      ,[Customer]
      ,[Bill-to Customer No_]
      ,[Service Type]
      ,[Service Type Option]
      ,[Unit of Measure Code]
      ,[Unit of Measure]
      ,[Qty_ per Unit of Measure]
      ,[Job Code]
      ,[Service Report]
      ,[Task]
      ,[Automatic Line Type]
      ,[Type]
      ,[Qty_ Available]
      ,[No_]
      ,[Attached to Line No_]
      ,[Job Code Setup]
      ,[Job Code Setup Line No_]
      ,[Equipment Category]
      ,[Equipment Group]
      ,[Equipment Model]
      ,[Description]
      ,[Description 2]
      ,[Variant Code]
      ,[Starting Date]
      ,[Starting Time]
      ,[Starting DateTime]
      ,[Finishing Date]
      ,[Finishing Time]
      ,[Finishing DateTime]
      ,[Activity Code]
      ,[User Overruled Location Code]
      ,[Location Code]
      ,[Bin Code]
      ,[Shelf_Bin No_]
      ,[Lot No_]
      ,[Serial No_]
      ,[Applies-to Item Entry]
      ,[Service Van]
      ,[No Warnings]
      ,[Quantity]
      ,[Quantity Base]
      ,[Not Billable]
      ,[Qty_ to Invoice]
      ,[Qty_ to Use]
      ,[Qty_ to Invoice Adjust]
      ,[Unit Price]
      ,[User Overruled Unit Price]
      ,[Original Unit Price]
      ,[Unit Cost]
      ,[Direct Unit Cost]
      ,[Line Cost]
      ,[Tax %]
      ,[Internal]
      ,[Line Discount %]
      ,[Line Discount Overrule]
      ,[Line Surcharge %]
      ,[Line Discount Amount]
      ,[Amount]
      ,[Internal Amount]
      ,[VAT Base Amount]
      ,[Amount incl_ Tax]
      ,[Quantity Used]
      ,[Quantity Used Base]
      ,[Qty_ to Use Base]
      ,[Qty_ to Invoice (Base)]
      ,[Quantity Invoiced]
      ,[Quantity Invoiced (Base)]
      ,[Amount Invoiced]
      ,[Amount Invoiced incl_ Tax]
      ,[Currency Code]
      ,[Gen_ Bus_ Posting Group]
      ,[Gen_ Prod_ Posting Group]
      ,[VAT Calculation Type]
      ,[VAT Bus_ Posting Group]
      ,[VAT Prod_ Posting Group]
      ,[Tax Area Code]
      ,[Tax Liable]
      ,[Tax Group Code]
      ,[Work Type Code]
      ,[Work Type Code Overrule]
      ,[Tariff Code]
      ,[Resource Price Reference No_]
      ,[Payroll Code]
      ,[Claim No_]
      ,[Claim]
      ,[Amount to Claim]
      ,[Barcode Scanning]
      
      ,[Buy-from Vendor No_]
      ,[Vendor Item No_]
      ,[Vendor Order No_]
      ,[Vendor Position No_]
      ,[Configurator]
      ,[Configurator Line No_]
      ,[Component Line No_]
      ,[Component No_]
      ,[Take from Object]
      ,[Outstanding Qty_ (Base)]
      ,[Expected Usage Date]
      ,[Budget Hours]
      ,[Budget Quantity]
      ,[Budget Unit Price]
      ,[Budget Amount]
      ,[Old]
      ,[Submitted Claim Amount]
      ,[Product Type]
      ,[Configurator Source]
      ,[Configurator Source Line No_]
      ,[Requisition Code]
      ,[Available]
      ,[Message Price && Availability]
      ,[Project No_]
      ,[Project Task]
      ,[Project Revision]
      ,[Project Task Line No_]
      ,[Project Budget Line No_]
      ,[Project not from Header]
      ,[Create New PO]
      ,[Suggested Purchase Order]
      ,[Maintenance Contract]
      ,[Maintenance Contract Line No_]
      ,[Shipment Method]
      ,[Installation Date]
      ,[Do Not Print]
      ,[Cylinder No_]
      ,[Nonstock Item]
     
      ,[Catalogue Header]
      ,[Catalogue Line]
      ,[Additional Qty_ to Order]
      ,[Waiting for Parts]
      ,[Parts Planning problem]
      ,[Direct Purchase Local Vendor]
      ,[Assigned parts]
      ,[Transport Status]
      ,[Unit Price source]
      ,[Unit price Source Record]
      ,[Reporting Code]
      ,[Total Together]
      ,[Manual Service Type]
      ,[Appl_-from Item Entry]
      ,[Placed on Work Order]
      ,[WO Quote - Order Line No_]
      ,[Object React_ Method]
      ,[User Change qty to use]
      ,[Tariff Multiplier]
      ,[Allow Line Disc_]
      ,[Resource Type]
      ,[Resource Group No_]
      ,[Service Type Source]
      ,[Posting Status]
      ,[Planned Service Action Date]
      ,[Non-Returnable]
      ,[User Overruled Job Code BOM]
      ,[Qty_ Used EveryWare]
      ,[Resource Allocation No_]
      ,[EveryWare Log]
      ,[Unit Price FC]
      ,[Line Discount Amount FC]
      ,[Line Amount FC]
      ,[Amount Invoiced FC]
  FROM [Copyofproduction ].[dbo].[Production$Work Order Line]
  WHERE [Document No_] LIKE 'S%'
  --AND [Purchase Document No_] <> ''
 AND [Document Type] ='1'
AND [Document No_] ='S0216517'




 --PURCHASE LINE 

 SELECT TOP (1000) [timestamp]
      ,[Document Type]
      ,[Document No_]
      ,[Line No_]
      ,[Buy-from Vendor No_]
      ,[Type]
      ,[No_]
       ,[Bin Code]
      ,[Location Code]
      ,[Posting Group]
      ,[Expected Receipt Date]
      ,[Description]
      ,[Description 2]
      ,[Unit of Measure]
      ,[Quantity]
      ,[Outstanding Quantity]
      ,[Qty_ to Invoice]
      ,[Qty_ to Receive]
      ,[Direct Unit Cost]
      ,[Unit Cost (LCY)]
      ,[VAT %]
      ,[Line Discount %]
      ,[Line Discount Amount]
      ,[Amount]
      ,[Amount Including VAT]
      ,[Unit Price (LCY)]
      ,[Allow Invoice Disc_]
      ,[Gross Weight]
      ,[Net Weight]
      ,[Units per Parcel]
      ,[Unit Volume]
      ,[Appl_-to Item Entry]
      ,[Shortcut Dimension 1 Code]
      ,[Shortcut Dimension 2 Code]
      ,[Job No_]
      ,[Phase Code]
      ,[Task Code]
      ,[Step Code]
      ,[Indirect Cost %]
      ,[Outstanding Amount]
      ,[Qty_ Rcd_ Not Invoiced]
      ,[Amt_ Rcd_ Not Invoiced]
      ,[Quantity Received]
      ,[Quantity Invoiced]
      ,[Receipt No_]
      ,[Receipt Line No_]
      ,[Profit %]
      ,[Pay-to Vendor No_]
      ,[Inv_ Discount Amount]
      ,[Vendor Item No_]
      ,[Sales Order No_]
      ,[Sales Order Line No_]
      ,[Drop Shipment]
      ,[Gen_ Bus_ Posting Group]
      ,[Gen_ Prod_ Posting Group]
      ,[VAT Calculation Type]
      ,[Transaction Type]
      ,[Transport Method]
      ,[Attached to Line No_]
      ,[Entry Point]
      ,[Area]
      ,[Transaction Specification]
      ,[Tax Area Code]
      ,[Tax Liable]
      ,[Tax Group Code]
      ,[Use Tax]
      ,[VAT Bus_ Posting Group]
      ,[VAT Prod_ Posting Group]
      ,[Currency Code]
      ,[Outstanding Amount (LCY)]
      ,[Amt_ Rcd_ Not Invoiced (LCY)]
      ,[Blanket Order No_]
      ,[Blanket Order Line No_]
      ,[VAT Base Amount]
      ,[Unit Cost]
      ,[System-Created Entry]
      ,[Line Amount]
      ,[VAT Difference]
      ,[Inv_ Disc_ Amount to Invoice]
      ,[VAT Identifier]
      ,[IC Partner Ref_ Type]
      ,[IC Partner Reference]
      ,[Prod_ Order No_]
      ,[Variant Code]
     
      ,[Qty_ per Unit of Measure]
      ,[Unit of Measure Code]
      ,[Quantity (Base)]
      ,[Outstanding Qty_ (Base)]
      ,[Qty_ to Invoice (Base)]
      ,[Qty_ to Receive (Base)]
      ,[Qty_ Rcd_ Not Invoiced (Base)]
      ,[Qty_ Received (Base)]
      ,[Qty_ Invoiced (Base)]
      ,[FA Posting Date]
      ,[FA Posting Type]
      ,[Depreciation Book Code]
      ,[Salvage Value]
      ,[Depr_ until FA Posting Date]
      ,[Depr_ Acquisition Cost]
      ,[Maintenance Code]
      ,[Insurance No_]
      ,[Budgeted FA No_]
      ,[Duplicate in Depreciation Book]
      ,[Use Duplication List]
      ,[Responsibility Center]
      ,[Cross-Reference No_]
      ,[Unit of Measure (Cross Ref_)]
      ,[Cross-Reference Type]
      ,[Cross-Reference Type No_]
      ,[Item Category Code]
      ,[Nonstock]
      ,[Purchasing Code]
      ,[Product Group Code]
      ,[Special Order]
      ,[Special Order Sales No_]
      ,[Special Order Sales Line No_]
      ,[Completely Received]
      ,[Requested Receipt Date]
      ,[Promised Receipt Date]
      ,[Lead Time Calculation]
      ,[Inbound Whse_ Handling Time]
      ,[Planned Receipt Date]
      ,[Order Date]
      ,[Allow Item Charge Assignment]
      ,[Return Qty_ to Ship]
      ,[Return Qty_ to Ship (Base)]
      ,[Return Qty_ Shipped Not Invd_]
      ,[Ret_ Qty_ Shpd Not Invd_(Base)]
      ,[Return Shpd_ Not Invd_]
      ,[Return Shpd_ Not Invd_ (LCY)]
      ,[Return Qty_ Shipped]
      ,[Return Qty_ Shipped (Base)]
      ,[Return Shipment No_]
      ,[Return Shipment Line No_]
      ,[Return Reason Code]
      ,[Tax To Be Expensed]
      ,[1099 Liable]
      ,[Pmt_ Discount Amount]
      ,[Suggested Line]
      ,[Non Deductible VAT %]
      ,[NOS Code]
      ,[Globalproduct id]
      ,[Rental Contract Type]
      ,[Rental Contract No_]
      ,[Rental Contract Line No_]
      ,[Equipment Category]
      ,[Equipment Group]
      ,[Equipment Model]
      ,[Equipment Object]
      ,[Cost Type]
      ,[Catalogue No_]
      ,[Physical Object]
      ,[Margin]
      ,[Work Order Type]
      ,[Work Order No_]
      ,[Work Order Line No_]
      ,[Configuration Item]
      ,[Equipment Serial No_]
      ,[Configurator Line No_]
      ,[Vendor Position No_]
      ,[Vendor Shipment Date]
      ,[Vendor Order No_]
      ,[P&&A Status]
      ,[P&&A Checked on]
      ,[P&&A Message]
      ,[D2V External Line No_]
      ,[Comment]
      ,[Trader Joe]
      ,[Order No_]
      ,[Order Line No_]
      ,[Receipt No_ Copy]
      ,[Receipt Line No_ Copy]
      ,[Qty_ Ordered]
      ,[Qty_ Ordered (Base)]
      ,[Qty_ Orginal Ordered]
      ,[D2V Reject Reason]
      ,[Onestop Shop Update version]
      ,[Tracking No_]
      ,[Normal Order]
      ,[Normal Order Sales No_]
      ,[Normal Order Sales Line No_]
      ,[Serials Required]
      ,[Assembly Item No_]
      ,[Project No_]
      ,[Project Task]
      ,[Project Task Line No_]
      ,[Project Revision]
      ,[Project Budget line]
      ,[Catalogue Header]
      ,[Catalogue Line]
      ,[Routing No_]
      ,[Operation No_]
      ,[Work Center No_]
      ,[Finished]
      ,[Prod_ Order Line No_]
      ,[Overhead Rate]
      ,[MPS Order]
      ,[Planning Flexibility]
      ,[Safety Lead Time]
      ,[Routing Reference No_]
      ,[Equipment Configurator No_]
      ,[D2V Interface]
      ,[Log File]
      ,[Claim No_]
      ,[Financing No_]
      ,[Financing Line No_]
      ,[D2V Price Code]
      ,[Cylinders Required]
      ,[D2V Order Status]
      ,[Reporting Code]
      ,[Manual Line Dimensions]
      ,[P&&A Suggested Catalogue No_]
      ,[User Overr_ Direct Unit Cost]
      ,[Lease Value Entries To Divide]
      ,[Auto Acc_ Group ELC]
      ,[Periodic Template Code ELC]
      ,[Periodic Starting Date ELC]
      ,[Maintenance Contract]
      ,[Maintenance Contract Line No_]
  FROM [Copyofproduction ].[dbo].[Production$Purchase Line]
  WHERE [Bin Code] = 'VAN'