SELECT TOP (1000) [timestamp]
      ,[Document Type]
      ,[No_]
      ,[Sell-to Customer No_]
      ,[Bill-to Customer No_]
      ,[Bill-to Name]
      ,[Bill-to Name 2]
      ,[Bill-to Address]
      ,[Bill-to Address 2]
      ,[Bill-to City]
      ,[Bill-to Contact]
      ,[Your Reference]
      ,[Ship-to Code]
      ,[Ship-to Name]
      ,[Ship-to Name 2]
      ,[Ship-to Address]
      ,[Ship-to Address 2]
      ,[Ship-to City]
      ,[Ship-to Contact]
      ,[Order Date]
      ,[Posting Date]
      ,[Shipment Date]
      ,[Posting Description]
      ,[Payment Terms Code]
      ,[Due Date]
      ,[Payment Discount %]
      ,[Pmt_ Discount Date]
      ,[Shipment Method Code]
      ,[Location Code]
      ,[Shortcut Dimension 1 Code]
      ,[Shortcut Dimension 2 Code]
      ,[Customer Posting Group]
      ,[Currency Code]
      ,[Currency Factor]
      ,[Customer Price Group]
      ,[Prices Including VAT]
      ,[Invoice Disc_ Code]
      ,[Customer Disc_ Group]
      ,[Language Code]
      ,[Salesperson Code]
      ,[Order Class]
      ,[No_ Printed]
      ,[On Hold]
      ,[Applies-to Doc_ Type]
      ,[Applies-to Doc_ No_]
      ,[Bal_ Account No_]
      ,[Job No_]
      ,[Ship]
      ,[Invoice]
      ,[Shipping No_]
      ,[Posting No_]
      ,[Last Shipping No_]
      ,[Last Posting No_]
      ,[VAT Registration No_]
      ,[Combine Shipments]
      ,[Reason Code]
      ,[Gen_ Bus_ Posting Group]
      ,[EU 3-Party Trade]
      ,[Transaction Type]
      ,[Transport Method]
      ,[VAT Country Code]
      ,[Sell-to Customer Name]
      ,[Sell-to Customer Name 2]
      ,[Sell-to Address]
      ,[Sell-to Address 2]
      ,[Sell-to City]
      ,[Sell-to Contact]
      ,[Bill-to Post Code]
      ,[Bill-to County]
      ,[Bill-to Country Code]
      ,[Sell-to Post Code]
      ,[Sell-to County]
      ,[Sell-to Country Code]
      ,[Ship-to Post Code]
      ,[Ship-to County]
      ,[Ship-to Country Code]
      ,[Bal_ Account Type]
      ,[Exit Point]
      ,[Correction]
      ,[Document Date]
      ,[External Document No_]
      ,[Area]
      ,[Transaction Specification]
      ,[Payment Method Code]
      ,[Shipping Agent Code]
      ,[Package Tracking No_]
      ,[No_ Series]
      ,[Posting No_ Series]
      ,[Shipping No_ Series]
      ,[Tax Area Code]
      ,[Tax Liable]
      ,[VAT Bus_ Posting Group]
      ,[Reserve]
      ,[Applies-to ID]
      ,[VAT Base Discount %]
      ,[Status]
      ,[Invoice Discount Calculation]
      ,[Invoice Discount Value]
      ,[Send IC Document]
      ,[IC Status]
      ,[Sell-to IC Partner Code]
      ,[Bill-to IC Partner Code]
      ,[IC Direction]
      ,[Doc_ No_ Occurrence]
      ,[Campaign No_]
      ,[Sell-to Customer Template Code]
      ,[Sell-to Contact No_]
      ,[Bill-to Contact No_]
      ,[Bill-to Customer Template Code]
      ,[Opportunity No_]
      ,[Responsibility Center]
      ,[Shipping Advice]
      ,[Posting from Whse_ Ref_]
      ,[Requested Delivery Date]
      ,[Promised Delivery Date]
      ,[Shipping Time]
      ,[Outbound Whse_ Handling Time]
      ,[Shipping Agent Service Code]
      ,[Receive]
      ,[Return Receipt No_]
      ,[Return Receipt No_ Series]
      ,[Last Return Receipt No_]
      ,[Service Mgt_ Document]
      ,[Expiration Date]
      ,[CP Status]
      ,[Auto Created]
      ,[Login ID]
      ,[Web Site Code]
      ,[Allow Line Disc_]
      ,[Get Shipment Used]
      ,[Ship-to UPS Zone]
      ,[Tax Exemption No_]
      ,[Consolidated Invoice]
      ,[Item No_]
      ,[Equipment Object]
      ,[Object Serial No_]
      ,[ELC Doc_ Type]
      ,[ELC Document No_]
      ,[Credit Approval No_]
      ,[Transaction Mode Code]
      ,[Bank Account Code]
      ,[Line Description Amount]
      ,[Line Description]
      ,[Financing No_]
      ,[Project No_]
      ,[Project Task]
      ,[Document User ID]
      ,[Created at Datetime]
      ,[Modified by]
      ,[Modification Datetime]
      ,[External Document No_ Required]
      ,[Ship or Pickup Sales]
      ,[Shipment Method]
      ,[Credit reason]
      ,[Credit User ID]
      ,[Credit datetime]
      ,[Credit invoice No_]
      ,[Not Over_ Post_ and Doc_ date]
      ,[Not Override Doc_ Date]
      ,[Journal Template Name]
      ,[Credit Type]
      ,[Requisition Code]
      ,[Date Received]
      ,[Time Received]
      ,[BizTalk Request for Sales Qte_]
      ,[BizTalk Sales Order]
      ,[Date Sent]
      ,[Time Sent]
      ,[BizTalk Sales Quote]
      ,[BizTalk Sales Order Cnfmn_]
      ,[Customer Quote No_]
      ,[Customer Order No_]
      ,[BizTalk Document Sent]
      ,[OLD 11095000]
      ,[OLD 11095001]
      ,[Calc_ Fin_ Lease  incl_ VAT]
      ,[Interest Rate]
      ,[Periods]
      ,[Rest Amount]
      ,[Interest Rate Manual Adjusted]
      ,[UserID Manual Interest Rate]
      ,[Calculated Amount Fin_ Lease]
      ,[Document Output Code]
      ,[Document Output Count]
      ,[Customer Price Group Parts]
      ,[Customer Price Group Resources]
      ,[Customer Price Group Charges]
      ,[Consolidated Order No_]
      ,[From Quote]
      ,[Agent]
      ,[Qualitiy Manager]
      ,[Belong to Main Object]
      ,[ELC Quote Type]
      ,[Version]
      ,[Salesperson Code 2]
      ,[Prepayment No_]
      ,[Last Prepayment No_]
      ,[Prepmt_ Cr_ Memo No_]
      ,[Last Prepmt_ Cr_ Memo No_]
      ,[Prepayment %]
      ,[Prepayment No_ Series]
      ,[Compress Prepayment]
      ,[Prepayment Due Date]
      ,[Prepmt_ Cr_ Memo No_ Series]
      ,[Prepmt_ Posting Description]
      ,[Prepmt_ Pmt_ Discount Date]
      ,[Prepmt_ Payment Terms Code]
      ,[Prepmt_ Payment Discount %]
      ,[Assigned User ID]
      ,[Print]
      ,[Manual Overruled Salesperon]
      ,[Use Sales Order Charges]
      ,[D2V Interface No_]
      ,[D2V Order Status]
      ,[Document Status]
      ,[Manufacturer Code]
      ,[Equipment Category]
      ,[Equipment Group]
      ,[Equipment Model]
  FROM [Copyofproduction ].[dbo].[Production$Sales Header]
  --where [On Hold] <> ''
  where [Status] = 0